import { ChangeDetectionStrategy, Component } from '@angular/core';
import { IconComponent, IconName } from '../../../../shared/icon/icon.component';

@Component({
  selector: 'app-ds-icons',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [IconComponent],
  templateUrl: './ds-icons.component.html',
  styleUrl: '../ds-page.scss',
})
export class DsIconsComponent {
  readonly icons: { name: IconName; label: string }[] = [
    { name: 'align-left', label: 'align-left' },
    { name: 'arrow-down-to-bracket', label: 'arrow-down-to-bracket' },
    { name: 'arrow-right-from-bracket', label: 'arrow-right-from-bracket' },
    { name: 'arrow-up-from-bracket', label: 'arrow-up-from-bracket' },
    { name: 'arrow-up-from-square', label: 'arrow-up-from-square' },
    { name: 'bars', label: 'bars' },
    { name: 'bell', label: 'bell' },
    { name: 'border-inner', label: 'border-inner' },
    { name: 'bullhorn', label: 'bullhorn' },
    { name: 'bullseye', label: 'bullseye' },
    { name: 'calculator', label: 'calculator' },
    { name: 'calendar', label: 'calendar' },
    { name: 'calendar-lines', label: 'calendar-lines' },
    { name: 'calendar-week', label: 'calendar-week' },
    { name: 'car-side', label: 'car-side' },
    { name: 'check', label: 'check' },
    { name: 'chevron-down', label: 'chevron-down' },
    { name: 'chevron-left', label: 'chevron-left' },
    { name: 'chevron-right', label: 'chevron-right' },
    { name: 'chevron-up', label: 'chevron-up' },
    { name: 'circle', label: 'circle' },
    { name: 'circle-info', label: 'circle-info' },
    { name: 'clipboard-user', label: 'clipboard-user' },
    { name: 'clock', label: 'clock' },
    { name: 'copy', label: 'copy' },
    { name: 'crosshairs-simple', label: 'crosshairs-simple' },
    { name: 'door-open', label: 'door-open' },
    { name: 'draw-circle', label: 'draw-circle' },
    { name: 'draw-polygon', label: 'draw-polygon' },
    { name: 'draw-square', label: 'draw-square' },
    { name: 'ellipsis', label: 'ellipsis' },
    { name: 'ellipsis-vertical', label: 'ellipsis-vertical' },
    { name: 'expand', label: 'expand' },
    { name: 'eye', label: 'eye' },
    { name: 'eye-slash', label: 'eye-slash' },
    { name: 'file', label: 'file' },
    { name: 'file-circle-exclamation', label: 'file-circle-exclamation' },
    { name: 'file-circle-info', label: 'file-circle-info' },
    { name: 'file-import', label: 'file-import' },
    { name: 'filter', label: 'filter' },
    { name: 'floppy-disk', label: 'floppy-disk' },
    { name: 'focus', label: 'focus' },
    { name: 'folder-open', label: 'folder-open' },
    { name: 'folder-tree', label: 'folder-tree' },
    { name: 'gear', label: 'gear' },
    { name: 'grip-dots', label: 'grip-dots' },
    { name: 'grip-dots-vertical', label: 'grip-dots-vertical' },
    { name: 'grip-lines', label: 'grip-lines' },
    { name: 'hexagon-check', label: 'hexagon-check' },
    { name: 'house', label: 'house' },
    { name: 'input-numeric', label: 'input-numeric' },
    { name: 'layer-group', label: 'layer-group' },
    { name: 'layer-minus', label: 'layer-minus' },
    { name: 'layer-plus', label: 'layer-plus' },
    { name: 'list', label: 'list' },
    { name: 'list-check', label: 'list-check' },
    { name: 'list-collection', label: 'list-collection' },
    { name: 'list-radio', label: 'list-radio' },
    { name: 'list-timeline', label: 'list-timeline' },
    { name: 'list-tree', label: 'list-tree' },
    { name: 'location-crosshairs', label: 'location-crosshairs' },
    { name: 'location-dot', label: 'location-dot' },
    { name: 'location-plus', label: 'location-plus' },
    { name: 'lock-keyhole', label: 'lock-keyhole' },
    { name: 'magnet', label: 'magnet' },
    { name: 'magnifying-glass', label: 'magnifying-glass' },
    { name: 'magnifying-glass-location', label: 'magnifying-glass-location' },
    { name: 'map', label: 'map' },
    { name: 'map-pin', label: 'map-pin' },
    { name: 'minus', label: 'minus' },
    { name: 'palette', label: 'palette' },
    { name: 'pen-line', label: 'pen-line' },
    { name: 'pin-viewfinder', label: 'pin-viewfinder' },
    { name: 'play', label: 'play' },
    { name: 'plus', label: 'plus' },
    { name: 'rotate-right', label: 'rotate-right' },
    { name: 'ruler', label: 'ruler' },
    { name: 'screen-users', label: 'screen-users' },
    { name: 'sensor-on', label: 'sensor-on' },
    { name: 'share-nodes', label: 'share-nodes' },
    { name: 'sidebar', label: 'sidebar' },
    { name: 'sliders', label: 'sliders' },
    { name: 'trash', label: 'trash' },
    { name: 'user', label: 'user' },
    { name: 'users', label: 'users' },
    { name: 'users-rectangle', label: 'users-rectangle' },
    { name: 'vigiante-logo', label: 'vigiante-logo' },
    { name: 'xmark', label: 'xmark' },
  ];
}
